import { GoogleGenAI, HarmCategory, HarmBlockThreshold } from "@google/genai";
import { GeminiModel } from "../types";

/**
 * Generates or edits an image based on an input image and a text prompt.
 * Uses Gemini 3 Pro Image Preview.
 * 
 * @param imageBase64 - The input image in base64 format (stripped of data:image/xyz;base64, prefix if possible, but the API handles cleaned base64)
 * @param prompt - The text instruction for the model
 * @param mimeType - The mime type of the input image
 * @returns Promise resolving to the base64 string of the generated image
 */
export const generateOrEditImage = async (
  imageBase64: string,
  prompt: string,
  mimeType: string = 'image/jpeg'
): Promise<string> => {
  try {
    // Initialize the Gemini client
    // process.env.API_KEY is injected by the environment
    // We create a new instance each call to ensure we pick up the latest key if it changed
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // Ensure clean base64 string
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, "");

    // Simplified instruction to act as a direct command, reducing risk of safety refusals for "person editing"
    const finalPrompt = `Apply the following style or edit to the provided image: ${prompt}. Ensure high quality output.`;

    const response = await ai.models.generateContent({
      model: GeminiModel.FLASH_IMAGE, // This is now mapped to gemini-3-pro-image-preview in types.ts
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
      config: {
        // Config for gemini-3-pro-image-preview
        imageConfig: {
          aspectRatio: "3:4", // Matches UI vertical aspect ratio
          imageSize: "1K" // Required/Available for Pro model
        },
        // Minimalist system instruction to avoid over-alignment issues
        systemInstruction: "You are a professional photo editor. Apply the requested style to the input image.",
        // Relax safety settings to BLOCK_NONE to prevent false positives on standard portraits
        safetySettings: [
          { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
          { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
          { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
          { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
          { category: HarmCategory.HARM_CATEGORY_CIVIC_INTEGRITY, threshold: HarmBlockThreshold.BLOCK_NONE },
        ],
      }
    });

    const candidate = response.candidates?.[0];

    // Log finish reason for debugging
    if (candidate?.finishReason) {
        console.log("Gemini Generation Finish Reason:", candidate.finishReason);
    }

    // Check for safety finish reason if no content
    if (!candidate?.content) {
        const reason = candidate?.finishReason;
        
        if (reason === 'SAFETY') {
            throw new Error("The generation was blocked due to safety concerns. Please try a different photo or prompt.");
        }

        // Handle "IMAGE_OTHER" or "OTHER" which often means the model refused the request due to policy.
        if (reason === 'OTHER' || reason === 'IMAGE_OTHER') {
             throw new Error("The AI model was unable to process this image due to content policy filters (Identity/Safety). Please try a different photo or style.");
        }
        
        if (reason) {
             throw new Error(`Generation stopped. Reason: ${reason}`);
        }
        throw new Error("No content generated by the model.");
    }

    // Iterate through parts to find the image
    const parts = candidate.content.parts;
    
    if (!parts || parts.length === 0) {
       if (candidate?.finishReason) {
             throw new Error(`Generation stopped. Reason: ${candidate.finishReason}`);
        }
       throw new Error("No content generated");
    }

    for (const part of parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    // If no image part found, maybe there's text explaining why (safety, etc)
    const textPart = parts.find(p => p.text);
    if (textPart) {
      console.warn("Model returned text instead of image:", textPart.text);
      // Clean error message for user
      throw new Error(`The model returned text instead of an image. Please try again or use a different photo.`);
    }

    throw new Error("No image data found in response");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};